POST http://localhost:8080/api/users
Content-Type: application/json

{
  "name": "keidasfdas",
  "email": "keiasdasd@example.com",
  "role": "participant"
}

###
GET http://localhost:8080/api/users


###
DELETE http://localhost:8080/api/users/675a36c9f48423f20649f14f


###
PATCH http://localhost:8080/api/users/675a34189fabaf7fff99c912
Content-Type: application/json

{
  "name": "sdaad",
  "email": "dasda.updated@example.com",
  "role": "participant"
}


###
POST http://localhost:8080/api/events
Content-Type: application/json

{
  "name": "Holiday Party",
  "date": "2024-12-25"
}


###
GET http://localhost:8080/api/events


###
DELETE http://localhost:8080/api/events/675a8241dd6e3b6e9a69aadb

###
PATCH http://localhost:8080/api/events/675a8241dd6e3b6e9a69aadb
Content-Type: application/json

{
  "name": "Updated Holiday Party",
  "date": "2024-12-31"
}
