POST http://localhost:8080/api/users
Content-Type: application/json

{
  "name": "sa",
  "email": "gpopoyan@email.com",
  "role": "participant"
}

###
GET http://localhost:8080/api/users


###
DELETE http://localhost:8080/api/users/67


###
PATCH http://localhost:8080/api/users/675a34189fabaf7fff99c912
Content-Type: application/json

{
  "email": "doooooo.updated@example.com",
  "role": "participant"
}


###
POST http://localhost:8080/api/events
Content-Type: application/json

{
  "name": "",
  "date": "2024-12-23"
}


###
GET http://localhost:8080/api/events


###
DELETE http://localhost:8080/api/events/675a8241dd6e3b6e9a69aadb

###
PATCH http://localhost:8080/api/events/675b2f3aeacbec5423095d6b
Content-Type: application/json

{
  "date": "2024-12-21"
}
